pathfinder/urls.py
from django.conf.urls import include
from django.urls import re_path

from . import views

app_name = 'pathfinder'

module_urls = [
    # Discord Service Control
    re_path(r'^activate/$', views.activate_pathfinder, name='activate'),
    re_path(r'^deactivate/$', views.deactivate_pathfinder, name='deactivate'),
]

urlpatterns = [
    re_path(r'^pathfinder/', include((module_urls, app_name), namespace=app_name))
]

pathfinder/models.py
from django.contrib.auth.models import User
from django.db import models


class PathfinderAccess(models.Model):
    user = models.OneToOneField(User,
                                primary_key=True,
                                on_delete=models.CASCADE,
                                related_name='pathfinder')

    def __str__(self):
        return "Pathfinder - {}".format(self.user.username)

    class Meta:
        permissions = (
            ("access_pathfinder", u"Can access Pathfinder on any linked character"),
        )

pathfinder/views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import redirect
from .models import PathfinderAccess
from .tasks import update_members

logger = logging.getLogger(__name__)

ACCESS_PERM = 'pathfinder.access_pathfinder'

@login_required
@permission_required(ACCESS_PERM)
def deactivate_pathfinder(request):
    PathfinderAccess.objects.filter(user=request.user).delete()
    update_members.apply_async(priority=3)
    return redirect("services:services")


@login_required
@permission_required(ACCESS_PERM)
def activate_pathfinder(request):
    pathfinder_user = PathfinderAccess()
    pathfinder_user.user = request.user
    pathfinder_user.save()
    update_members.apply_async(priority=3)
    return redirect("services:services")

pathfinder/templates/services/pathfinder/pathfinder_service.html
{% extends "services/services_ctrl_base.html" %}

{% load i18n %}

{% block title %}
Pathfinder
{% endblock %}

{% block active %}
    {% include "services/service_status.html" with username=user.pathfinder %}
{% endblock active %}




{% block url %}
    <a href="{{ PATHFINDER_URL  }}">{{ PATHFINDER_NAME  }}</a>
    {% endblock %}

    {% block user %}
    <p >All Linked Character</p>
    {% endblock %}

    {% block controls %}
    {% if not user.pathfinder %}
    <a href="{% url 'pathfinder:activate' %}" title="Reset" class="btn btn-warning">
                <i class="fa-solid fa-check fa-fw"></i>
    </a>
    {% else %}
    <a href="{% url 'pathfinder:deactivate' %}" title="Deactivate" class="btn btn-danger">
                <i class="fa-solid fa-xmark fa-fw"></i>
    </a>
    {% endif %}
    {% endblock %}